repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1500']
        exclude: ^crypto_sentiment_demo_app/frontend
    -   id: check-docstring-first
        exclude: ^crypto_sentiment_demo_app/frontend
    -   id: check-yaml
        exclude: ^crypto_sentiment_demo_app/frontend
    -   id: end-of-file-fixer
        exclude: ^crypto_sentiment_demo_app/frontend
    -   id: trailing-whitespace
        exclude: ^crypto_sentiment_demo_app/frontend
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["--config=pyproject.toml"]
        exclude: ^crypto_sentiment_demo_app/frontend
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--config", ".flake8"]
        exclude: ^crypto_sentiment_demo_app/frontend
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", "-v"]
        exclude: ^crypto_sentiment_demo_app/frontend
