repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1500']
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude:  |
            (?x)^(
                crypto_sentiment_demo_app/frontend|
                actions-runner
            )$
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: ["--config=pyproject.toml"]
        exclude:  |
            (?x)^(
                crypto_sentiment_demo_app/frontend|
                actions-runner
            )$
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: ["--config", ".flake8"]
        exclude:  |
            (?x)^(
                crypto_sentiment_demo_app/frontend|
                actions-runner
            )$
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
        exclude:  |
            (?x)^(
                crypto_sentiment_demo_app/frontend|
                actions-runner
            )$
