data:
  path_to_data: data                          # Local path where the train and validation data should be placed
                                              # in order to run the model training
  text_field_name: title
  label_field_name: sentiment
  num_classes: 3
  max_text_length_words: 500
  class_names: ["Negative", "Neutral", "Positive"]

model:                                        # Params of the model defined in src/model.py
  name: "Tf-Idf & logreg"                     # TODO replace this with setting up MLFlow tracking
  version: 0.1.0                              # TODO replace this with setting up MLFlow tracking
  path_to_model: static/models/logit_tfidf_btc_sentiment.pkl # TODO replace this with setting up MLFlow tracking

database:
  path_to_connection_param_file: db_connection.ini

logging:
  version: 1
  formatters:
    app:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: app
      stream: ext://sys.stdout
  loggers:
    appLogger:
      level: INFO
      handlers: [console]
      propagate: no
  root:
    level: INFO
    handlers: [console]