version: '3.9'

services:
  crawler:
    image: basic_image_crawler
    build: crypto_sentiment_demo_app/crawler
    command: python3 -m crypto_sentiment_demo_app.crawler.crawler
    volumes:
      - ./:/root
      -
  model_inference_api:
    image: basic_image_model_fast_api
    build: crypto_sentiment_demo_app/model_inference_api
    command: uvicorn crypto_sentiment_demo_app.model_inference_api.api:app --host model_inference_api --reload
    volumes:
      - ./:/root
    ports:
      - "8000:8000"
    hostname: model_inference_api

  model_scorer:
    image: basic_image_model_scorer
    build: crypto_sentiment_demo_app/model_scorer
    command: python3 -m crypto_sentiment_demo_app.model_scorer.model_scorer
    volumes:
      - ./:/root
    depends_on:
      - model_inference_api
    links:
      - model_inference_api

  frontend:
      image: basic_image_streamlit
      build: crypto_sentiment_demo_app/frontend
      command: streamlit run crypto_sentiment_demo_app/frontend/streamlit_app.py
      ports:
        - "8501:8501"
      volumes:
        - ./:/root
      depends_on:
        - model_inference_api
      links:
        - model_inference_api