version: '3.9'

services:
  crawler:
    image: basic_image_crawler
    build: crypto_sentiment_demo_app/crawler
    command: python3 -m crypto_sentiment_demo_app.crawler.crawler
    volumes:
      - ./:/root
    profiles:
      - production

  model_inference_api:
    image: basic_image_model_fast_api
    build: crypto_sentiment_demo_app/model_inference_api
    command: uvicorn crypto_sentiment_demo_app.model_inference_api.api.model:app --host model_inference_api --port 8001 --reload
    volumes:
      - ./:/root
    ports:
      - "8001:8001"
    hostname: model_inference_api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://model_inference_api:8001/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    profiles:
      - production

  model_scorer:
    image: basic_image_model_scorer
    build: crypto_sentiment_demo_app/model_scorer
    command: python3 -m crypto_sentiment_demo_app.model_scorer.model_scorer
    volumes:
      - ./:/root
    depends_on:
      model_inference_api:
        condition: service_healthy
    links:
      - model_inference_api
    profiles:
      - production

  data_provider:
    image: basic_image_data_provider
    build: crypto_sentiment_demo_app/data_provider
    command: uvicorn crypto_sentiment_demo_app.data_provider.api:app --host data_provider --port 8002 --reload
    ports:
      - "8002:8002"
    volumes:
      - ./:/root
    hostname: data_provider
    healthcheck:
      test: ["CMD", "curl", "-f", "http://data_provider:8002/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    profiles:
      - production

  frontend:
    image: basic_image_streamlit
    build: crypto_sentiment_demo_app/frontend
    command: streamlit run crypto_sentiment_demo_app/frontend/streamlit_app.py
    ports:
      - "8501:8501"
    volumes:
      - ./:/root
    depends_on:
      model_inference_api:
        condition: service_healthy
      data_provider:
        condition: service_healthy
    links:
      - model_inference_api
      - data_provider
    profiles:
      - production

  train:
    image: basic_image_train
    build:
      context: crypto_sentiment_demo_app/train
      args:
        USER_ID: "$USER"
        GROUP_ID: "$GROUP"
      dockerfile: Dockerfile-cpu
    command: python3 crypto_sentiment_demo_app/train/train.py
    volumes:
      - ./:/root
    profiles:
      - train
