[tool.black]
line-length = 119
target-version = ['py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.tox
  | \*venv
)/
'''

[tool.isort]
skip = ["crypto_sentiment_demo_app/mlflow_server/create_bucket.py"]
