data:
  text_field_name: title
  label_field_name: sentiment
  path_to_data: data/
  train_filename: 20190110_train_4500.csv
  class_names: ["Negative", "Neutral", "Positive"]

crawler:
  url: "https://bitcointicker.co/news/"

inference_api:
  host_name: model_inference_api
  port: 8001
  endpoint_name: classify

database:
  path_to_connection_param_file: db_connection.ini
  content_table_name: news_titles
  content_index_name: title_id
  model_pred_table_name: model_predictions

# Hydra logging boilerplate
defaults:
  - _self_
  - model: tf_idf
  - logger: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
