FROM python:3.9-slim

WORKDIR /root

RUN apt update -y && \
    apt upgrade -y && \
    apt install -y curl locales locales-all && \
    apt-get install -y sudo && \
    rm -rf /var/lib/apt/lists/*

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

ARG USER_ID
ARG GROUP_ID

# Create a non-root user and switch to it
RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID --shell /bin/bash user \
    && chown -R user:user /root
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

COPY requirements-cpu.txt /root
RUN python -m pip install --upgrade pip
RUN pip3 install -r requirements-cpu.txt --no-cache-dir

ENV PYTHONPATH "${PYTHONPATH}:/root/crypto_sentiment_demo_app"
ENV PYTHONPYCACHEPREFIX=/tmp/cpython/
